# Generated by Django 5.1.7 on 2025-03-21 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_officer'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='complaint_photos/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('status_code', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aadhaar_photo', models.ImageField(blank=True, null=True, upload_to='aadhaar_photos/%Y/%m/%d/')),
                ('date_of_incident', models.DateField(blank=True, null=True)),
                ('proof_of_work', models.ImageField(blank=True, null=True, upload_to='proof_of_work/%Y/%m/%d/')),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.officer')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.category')),
            ],
        ),
    ]
