# Generated by Django 5.1.7 on 2025-03-21 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_complaints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='email',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='name',
        ),
        migrations.AddField(
            model_name='complaints',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='userapp.userreg'),
            preserve_default=False,
        ),
    ]
