# Generated by Django 5.1.7 on 2025-03-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_complaints_email_remove_complaints_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='proof_of_work',
            field=models.FileField(blank=True, null=True, upload_to='proof_of_work/%Y/%m/%d/'),
        ),
    ]
