# Generated by Django 5.1.7 on 2025-03-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_complaints_proof_of_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaints',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
