# Generated by Django 5.1.7 on 2025-03-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
