# Generated by Django 5.1.7 on 2025-03-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='proof_of_work',
            field=models.ImageField(blank=True, null=True, upload_to='proof_of_work/%Y/%m/%d/'),
        ),
    ]
